global:
  scrape_interval: 15s  # กำหนดช่วงเวลาเริ่มต้นในการดึงข้อมูล (scrape) ทุกๆ 15 วินาที

scrape_configs:
  - job_name: 'prometheus'  # ชื่อ job สำหรับ Prometheus
    scrape_interval: 5s  # กำหนดช่วงเวลาในการดึงข้อมูล (scrape) สำหรับ job นี้ทุกๆ 5 วินาที
    static_configs:
      - targets: ['localhost:9090']  # กำหนดเป้าหมาย (target) คือ Prometheus เองที่รันอยู่บนพอร์ต 9090

  - job_name: 'mysqld-exporter'  # ชื่อ job สำหรับ MySQL exporter
    static_configs:
      - targets: ['mysqld-exporter:9104']  # กำหนดเป้าหมาย (target) คือ mysqld-exporter ที่รันอยู่บนพอร์ต 9104
  
  - job_name: 'flask-api'  # ชื่อ job สำหรับ Flask API
    metrics_path: /metrics  # กำหนดเส้นทาง (path) สำหรับดึงข้อมูล metrics
    static_configs:
      - targets: ['flask-api:5000']  # กำหนดเป้าหมาย (target) คือ Flask API ที่รันอยู่บนพอร์ต 5000
